Add old Plone 5 classes to the portlet template
plone/plone.app.event pull request #417
Opened 2024-11-26 22:27 UTC by thet

Add Plone 5 classes portletHeader and portletContent to the portlet template to improve compatibility with Plone 5 styles.
This can help when migrating styles from Plone 5 to Plone 6.

Note: This targets only portlets yet. There is probably much more to do to improve the Plone 5 to 6 upgrade experience.

2024-11-26 22:27 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-11-28 10:18 UTC, thet commented
@jenkins-plone-org please run jobs

2025-01-23 15:49 UTC, mauritsvanrees reviewed
This is not my area of expertise.

I don't see these classes in the portlets in `plone.app.portlets` either.

2025-01-24 06:52 UTC, petschki requested changes
Two thoughts:

1. I'm not sure if it really helps to mix possible "old" `.plonePortlet` classes with the `.card` utility. You have to put your hands on both scenarios either way.
2. the portlet templates are spread over various packages so I'd wait for the template merge and add it afterwards (or during the merging)

2025-02-28 11:22 UTC, thet commented
I‌ had issues when upgrading a theme from Plone 5 to 6.
But I agree, there is a lot to adapt, let's go forward.

2025-02-28 11:22 UTC, closed without merging